<?php 
//IP DEL SERVIDOR DE BASE DE DATOS
define("DB_HOST", "sql10.freesqldatabase.com");

//NOMBRE DE LA BASE DE DATOS
define("DB_NAME", "sql10526981");

//NOMBRE DEL USUARIO DE LA BASE DE DATOS
define("DB_USERNAME", "sql10526981");

//CLAVE DEL USUARIO DE LA BASE DE DATOS
define("DB_PASSWORD", "1JNVx1GT7s");

//CODIFICACION DE LOS CARACTERES
define("DB_ENCODE", "utf8");

//CONSTANTE COMO NOMBRE DEL PROYECTO
define("PRO_NOMBRE", "PowerGym");
?>